### ISSUE TITLE
sorry to make a issue for this but how do you compile this?

### ISSUE THREAD

**Issue by EmissaryOfToddHoward** [Exitium-DEV/HD2-Cheat-Launcher#7]

**Comment by DeathWrench** [comment]
![image](https://github.com/Exitium-DEV/HD2-Cheat-Launcher/assets/45341450/416a06f1-99f5-4cd2-9ef8-c812a02da2a5)
![image](https://github.com/Exitium-DEV/HD2-Cheat-Launcher/assets/45341450/456c4475-9ad0-4090-a4e4-cc94d4701696)
![image](https://github.com/Exitium-DEV/HD2-Cheat-Launcher/assets/45341450/cc30b47d-2054-46e6-8970-95fbfc7742e1)
![image](https://github.com/Exitium-DEV/HD2-Cheat-Launcher/assets/45341450/70bcf513-bc6b-4477-9f6f-8877a160aa6d)
![image](https://github.com/Exitium-DEV/HD2-Cheat-Launcher/assets/45341450/af4003e8-c4e8-49e2-836a-279e98ea6687)

**Comment by Glockys1000** [comment]
when clicking publish nothing happens any idea?

**Comment by DeathWrench** [comment]
> when clicking publish nothing happens any idea? edit: was able to publish, but what am i meant to do with the files in the folder once it does publish? I am new to modding into this depth.
#### HD2-Cheat-Launcher\bin\Release\net8.0\win-x64\publish\win-x64\HD2 Hacked Launcher.exe
You just made what is posted here: https://github.com/Exitium-DEV/HD2-Cheat-Launcher/releases/latest

How to use: https://github.com/Exitium-DEV/HD2-Cheat-Launcher#usage

**Comment by Glockys1000** [comment]
I see thank you for the quick reply. So I do not need to download the helldivers2.exe? I use the HD2 Hacked Launcher.exe I just published correct?

**Comment by Glockys1000** [comment]
I just got it to work and opened up the game and about 3 minutes in said it was detected. That was the same issue I had before publishing. Is there extra steps that need to be done to not get detected?

**Comment by JourneyOver** [comment]
Nah Glocksys there isn't really much you can do short of going and modifying the code over at https://github.com/emoisback/Helldivers-2-Internal-Hack-Dll-Proxy-PoC and creating your own version.dll file, as this isn't a foolproof plan at all sadly as the file will still get detected from time to time (from my own testing)

**Comment by DeathWrench** [comment]
> I just got it to work and opened up the game and about 3 minutes in said it was detected. That was the same issue I had before publishing. Is there extra steps that need to be done to not get detected? Ive followed all the steps at least I thought correctly.

You can try my fork without the console enabled. (https://github.com/DeathWrench/Helldivers-2-Internal-Hack-Dll-Proxy-PoC) You need to edit dllmain.cpp to edit the true/false values to what you want though.

**Comment by Glockys1000** [comment]
> > I just got it to work and opened up the game and about 3 minutes in said it was detected. That was the same issue I had before publishing. Is there extra steps that need to be done to not get detected? Ive followed all the steps at least I thought correctly.
> 
> You can try my fork without the console enabled. (https://github.com/DeathWrench/Helldivers-2-Internal-Hack-Dll-Proxy-PoC) You need to edit dllmain.cpp to edit the true/false values to what you want though.

Sorry I am quite dumb, I was able to edit and all that but how do I go about launching the game now? and do I just revert back to putting the version.dll from emoisback in the game folder?

**Comment by Glockys1000** [comment]
![image](https://github.com/Exitium-DEV/HD2-Cheat-Launcher/assets/113270005/91fa755a-38b4-48d2-bafb-5d63fe447b73)

**Comment by Glockys1000** [comment]
Just downloaded the correct version.dll from the actions but the console still popped up when launching the game

**Comment by GICK11** [comment]
![image](https://github.com/Exitium-DEV/HD2-Cheat-Launcher/assets/162613275/ecb28d45-ce59-4602-bc05-e2ae67790ee3)
im still getting this message even if i set it on the right path

**Comment by Glockys1000** [comment]
> Nah Glocksys there isn't really much you can do short of going and modifying the code over at https://github.com/emoisback/Helldivers-2-Internal-Hack-Dll-Proxy-PoC and creating your own version.dll file, as this isn't a foolproof plan at all sadly as the file will still get detected from time to time (from my own testing)

Is there a way you can link your dll? I have no idea about coding so creating my own version.dll file sounds like something that I have no idea about.

**Comment by DeathWrench** [comment]
>im still getting this message even if i set it on the right path
![image](https://github.com/Exitium-DEV/HD2-Cheat-Launcher/assets/45341450/aefeb89d-87f3-444b-b475-270e293439ce)

**Comment by Glockys1000** [comment]
> You can try my fork without the console enabled. (https://github.com/DeathWrench/Helldivers-2-Internal-Hack-Dll-Proxy-PoC) You need to edit dllmain.cpp to edit the true/false values to what you want though.

Where do I need to put all the files from Helldivers-2-Internal-Hack-Dll-Proxy-PoC-master for example the dllmain.cpp file i edited?

**Comment by DeathWrench** [comment]
> > Nah Glocksys there isn't really much you can do short of going and modifying the code over at https://github.com/emoisback/Helldivers-2-Internal-Hack-Dll-Proxy-PoC and creating your own version.dll file, as this isn't a foolproof plan at all sadly as the file will still get detected from time to time (from my own testing)
> 
> Is there a way you can link your dll? I have no idea about coding so creating my own version.dll file sounds like something that I have no idea about.

You go to this link:
- https://github.com/DeathWrench/Helldivers-2-Internal-Hack-Dll-Proxy-PoC
- click
![image](https://github.com/Exitium-DEV/HD2-Cheat-Launcher/assets/45341450/34b69715-9ca3-4258-b004-011e02266154)
- go here: https://github.com/Glockys1000/Helldivers-2-Internal-Hack-Dll-Proxy-PoC/actions and make sure workflows enabled.
- then go here: https://github.com/Glockys1000/Helldivers-2-Internal-Hack-Dll-Proxy-PoC/blob/master/version/dllmain.cpp and click 
![image](https://github.com/Exitium-DEV/HD2-Cheat-Launcher/assets/45341450/e7a9e4a9-f55a-46f7-9125-b29bc278ac39)
- edit these values to what you want enabled/disabled and commit the changes to your fork:
```
          {_XOR_("Inf Health"), true}
        , {_XOR_("Inf Grenades"), false}
        , {_XOR_("Inf Grenades(Legit)"), true}
        , {_XOR_("Inf Ammo"), false}
        , {_XOR_("Inf Ammo(Legit)"), true}
        , {_XOR_("Inf Syringes"), false}
        , {_XOR_("Inf Syringes(Legit)"), true}
        , {_XOR_("Inf Stamina"), true}
        , {_XOR_("Inf Stratagems"), true}
        , {_XOR_("MoveSpeed X6"), false}
        , {_XOR_("Inf Mission Time"), false}
        //, {"One / Two Hit Kill ( Bile Titan Bug, Aim Only Head )", false}
        , {_XOR_("No Reload"), true}
        , {_XOR_("No Reload V2"), true}
        , {_XOR_("Max Resources"), false}
        , {_XOR_("Add 5 Samples"), false}
        , {_XOR_("No Recoil"), true}
        , {_XOR_("Inf Backpack"), true}
        , {_XOR_("Inf Special Weapon"), false}
        , {_XOR_("No Laser Cannon Overheat"), false}
        , {_XOR_("Instant Railgun"), false}
        , {_XOR_("Show All Map Icons"), true}
        , {_XOR_("No Stationary Turret Overheat"), false}
        , {_XOR_("No Backpack Shield Cooldown"), true}
        , {_XOR_("No JetPack Cooldown"), false}
        , {_XOR_("All Stratagems in Loadout"), false}
        , {_XOR_("All Equipment in Armory"), false}
        , {_XOR_("All Armor in Armory"), false}
```
- Go back here: https://github.com/Glockys1000/Helldivers-2-Internal-Hack-Dll-Proxy-PoC/actions to get your version.dll

Or just clone it in visual studio and edit the file there, compile it in VS.
